### PR TITLE
Use the new TweetDeck official icon-set for BTD icons

### PR DESCRIPTION
**Pull request by LeoColomb**
🌈

### CODE REVIEW

**Comment by eramdam** [comment]
@LeoColomb can I see a screenshot of the emoji/poll thing?

**Comment by LeoColomb** [comment]
Icon|Before|After
---|---|---
Emoji|image|image
Poll|image|image

**Comment by eramdam** [comment]
The emoji is 👌  but the poll icon is less legible now. I would keep the old poll icon but use the new emoji icon.

**Comment by LeoColomb** [comment]
> the poll icon is less legible now

What do you mean? 😸

**Comment by eramdam** [comment]
@LeoColomb it's messier than before, I don't think the stroke icons are meant to be displayed at such a small size

**Comment by LeoColomb** [comment]
But on the other hand it's the new official Twitter icon/design for poll relative buttons...

image

**Comment by eramdam** [comment]
Let's merge it and I'll see how it goes.

**Comment by LeoColomb** [comment]
As you want! 😄

**Comment by LeoColomb** [comment]
> I'll see how it goes.

Well, [no more necessary](https://twitter.com/TweetDeck/status/877536207034568704)! 😆 

In fact poll button addition should be removed...
image

**Comment by eramdam** [comment]
I already pushed a commit for that. I still have to do a release 😅

**Pull request merged**
