### PR TITLE
iOS 9.1 / Unicode 8.0 emojis and more

### PR DESCRIPTION
**Pull request by rodrigopolo**
1. I have added all emojis available on iOS 9.1 / OS X 10.11.1  
  Emojis
2. I have commented a bug I found in `usefulFunctions.js` named `ResizeMediaInModal()`, it looks like it cannot find the css selector.
3. I have added Spanish translation.
4. I have modified the emoji css file to use a single class for the image background and size.

I know that the emojis included (the PNG sprites) are using the last Apple emojis and not [Twemoji](https://github.com/twitter/twemoji) emojis, but they have not updated their catalog.

I strongly recommend to switch to [Emoji One](https://github.com/Ranks/emojione) when they release their 2016 collection on November, I also redomend to use their [Shortname Autocomplete](http://git.emojione.com/demos/1.5.0/autocomplete.html) for faster emoji input.

I belive there could be a bug or unused code because I changed the name on the emoji panel, so maybe some css/js selectors are not being used.

I have tested the app and it works great.

### CODE REVIEW

**Comment by eramdam** [comment]
@rodrigopolo 
First thing: can you do a separate PR for the ES translation?

Second thing: I'm not adding any new emojis until Twitter update its collection, and I don't want to have different looking emojis between the picker and the tweet columns. And I don't want to add the shortname feature, it would be VERY messy to modify the character counter, but I could easily add a "search" input on the emoji panel on BTD 3.0.

**Comment by rodrigopolo** [comment]
1 - Done, I submitted the translation in other commit.  

2 - About the "short name" feature, I mean something like this:
emoji-input

Demo available here:
http://rodrigopolo.com/files/emoji-input/

3 - Twemoji is taking too long to update their emojis, that's why I added the new emoji to BetterTweetDeck and making them show their short tag name (title property on the anchor):

emojis

I have also added a replacement for the emoji replacer, using the same sprite, but I'm currently changing the script to load each png to comply with TweetDeck standard so text can be copied and viewed as expected.

replacer

You should consider using this pngs because Apple is always the first to update it, ask your users about that, I'm quite sure they will prefer Apple emojis over any other.

All changes are already committed on my fork in case you want to see them.

Cheers!

**Comment by rodrigopolo** [comment]
Done! My last commit to my fork has the Apple emojis as images:

retina

And they are HiDPI / Retina ready:
emojis

**Comment by eramdam** [comment]
Interesting. I'll look at that once I'm far enough in writing 3.0 :)

**Comment by eramdam** [comment]
@rodrigopolo I can't see your fork anymore, Github says the repo has been deleted :(

**Comment by rodrigopolo** [comment]
I deleted and then made another fork, it is here: https://github.com/rodrigopolo/BetterTweetDeck

**Comment by Twilightssuperb** [comment]
FYI, last week Twemoji had been updated. Now it includes new emojis: 
http://blog.emojipedia.org/twemoji-2-0-emoji-changelog/

**Comment by rodrigopolo** [comment]
About time.

**Comment by eramdam** [comment]
@rodrigopolo im waiting for your commit with the new twemoji and then I will merge this 👌

**Comment by rodrigopolo** [comment]
I will, I'm just finishing some client's project and then I'll put all my energy on this.

**Comment by eramdam** [comment]
@rodrigopolo no worries! Thanks for your hard work :)

**Pull request closed without merging**
