### PR TITLE
Feature/display milisec

### PR DESCRIPTION
**Pull request by key-moon**
### OverView
Add an option to replace timestamp with result of parsed SnowFlake.
image
image

### Details
Twitter assigns an ID called SnowFlake to the ID of each tweet. It contains information in milliseconds.
I can use a href attribute of timestamp to get SnowFlake(Timestamp is also a link to the tweet).
Old ID is just a serial,there is no information of time. so, If Tweet's ID is old one, I calculate from data-time like the current method.
Time may not be displayed correctly right after loading, this is a bug from the old version. I tried to fix this, but I could not identify where the problem occurred.
image

### Disclaimer
I am Japanese and I am anxious about my English sentences. I am sorry in my poor English.

### CODE REVIEW

**Comment by key-moon** [comment]
I really want to publish this feature. If you have any problem for merge this PR, Please give me comment.

**Comment by eramdam** [comment]
@key-moon Hi! I'm very sorry for the late reply/inactivity here. Your PR doesn't have any issue whatsoever, I just didn't have time to focus on merging PRs those past few months. 

I hope to be able to do that later this month, sorry if I gave the impression there was an issue 😞

**Comment by eramdam** [comment]
@key-moon I finally got time to review the PR properly. I have a few thoughts:

Would it be possible to **always** parse the "precise" date and remove the setting entirely? I feel like we could do that and then people could use the `SSS` token if they need to, since it's documented in the `fecha` help linked in the settings.

This would make the feature easier to use I think. Unless there is a performance cost to parsing the snowflake thing by default? I couldn't see any but maybe I'm missing something.

**Comment by key-moon** [comment]
@eramdam I'm sorry for my late reply.
Yes, I agree your opinion. There is no cost such became problems, and we don't want to settings become complicated. On the other hand, I feel like should make a way for users to change.(for example,make ”don't use presice time”option or something like that.)

That is hard problem, so I leave it to your judgment.

**Comment by eramdam** [comment]
I'm closing this PR and will try to port its content into the v4 codebase when I merge it.

**Comment by eramdam** [comment]
Merged in [4.5.2](https://github.com/eramdam/BetterTweetDeck/releases/tag/4.5.2) !

**Pull request closed without merging**
