### PR TITLE
Add a thumbnail support for miil.me

### PR DESCRIPTION
**Pull request by shuuji3**
[miil.me](https://miil.me) is a food photo sharing service. Please search **#miil** hashtags to test tweets.

I need to use `$.getSafeURL` twice in `src/js/util/providers/miil.js` because miil's API always returns **http** URL even if we request **https** URL. For example, when we get an image for **https**://miil.me/p/bmex6 and request **https**://miil.me/p/bmex6.jpeg, miil's API always responses **http**://images.miil.me/j/706b1c90-e855-11e7-b212-22000aba80ad.jpg (http URL). Do you know the way to avoid using `$.getSafeURL` twice?

API document (only Japanese):
https://github.com/FrogAppsDev/miil-apis/tree/master/Japanese

### CODE REVIEW

**Comment by eramdam** [comment]
@shuuji3 `getSafeURL` should work regardless of HTTP or HTTPS, what's happening if you use it only once? https://github.com/eramdam/BetterTweetDeck/blob/master/src/js/util/thumbnails.js#L40

**Comment by shuuji3** [comment]
**http** request to image URL happens.

 In the console:


miil's API implements by HTTP 302 redirect. So I assume that first `getSafeURL` calling was used to get second http://images.miil.me/〜.jpeg URL.

**Comment by eramdam** [comment]
@shuuji3 can't you just pass a version of the URL with `https` instead of `http`? 🤔

**Comment by eramdam** [comment]
@shuuji3 also, I got a HTTPS image just fine here https://images.miil.me/j/706b1c90-e855-11e7-b212-22000aba80ad.jpg=s576

**Comment by shuuji3** [comment]
Actually, I give the URL with `https` (like ` https://miil.me/p/bmex6.jpeg`) to `getSafeURL` [here](https://github.com/eramdam/BetterTweetDeck/pull/294/files#diff-324b69da3ea276c464759ac8ae7e87c3R9).

When I write a callback like this:
```javascript
    callback: url => Promise.resolve({
      type: 'image',
      thumbnail_url: $.getSafeURL(`${url}.jpeg`),
      url: $.getSafeURL(`${url}.jpeg`),
    }),
```
`http` request happens.



But with double `getSafeURL`:
```javascript
    callback: url => Promise.resolve({
      type: 'image',
      thumbnail_url: $.getSafeURL($.getSafeURL(`${url}.jpeg`)),
      url: $.getSafeURL($.getSafeURL(`${url}.jpeg`)),
    }),
```
The request with proxy properly happens.


I don't know where to replace `http://` with `https://` before the request happens.

**Comment by eramdam** [comment]
@shuuji3 just replace `https` by `http` and use $.getSafeURL once and it works. (I tried it locally and it works just fine)

**Comment by shuuji3** [comment]
Thanks! The problem has been fixed. I totally thought I must use https...

**Pull request merged**
