### PR TITLE
Fix media overflow when using small windows

### PR DESCRIPTION
**Pull request by arontx**
Expanding media overflows for small screens/windows e.g.

before

Issue seems to be with this:
https://github.com/eramdam/BetterTweetDeck/blob/6c97232780c8539d5ec4f8768a6094420830cf2f/src/css/features/no-bg-modal.css#L40

You can workaround it by adding this to your Custom CSS
html.btd-on .btd__no_bg_modal .med-embeditem{min-width:0px}

e.g.

after

### CODE REVIEW

**Comment by arontx** [comment]
> Thanks for that PR! I see you're touching only the `no_bg_modal` part of the CSS, isn't that bug occurring without the setting turned on too?

To be honest, I'm not sure which setting it is!

When I searched, I didn't see `min-width: 600px` declaration anywhere else in the project. I suppose other min-width declarations could be causing a similar problem (i.e. YouTube embeds) but I didn't run into it.

**Comment by eramdam** [comment]
@arontx the setting is `Hide background behind fullscreen previews` under the `Interface` section.

**Comment by arontx** [comment]
@eramdam Tested just now and if you disable the setting the media does not overflow. As far as I can tell, the bug doesn't occur with the setting disabled (the computed min-width of .med-embeditem is 0px).

**Comment by eramdam** [comment]
Oh ok. I'll try to check **why** I put the min-width in the first place. There probably was a reason back then... 😅

**Pull request merged**
