### PR TITLE
🇯🇵 add ja locale

### PR DESCRIPTION
**Pull request by shuuji3**
Hello, I translated messages for Japanese users. Could you marge these? Thank you.

### CODE REVIEW

**Comment by eramdam** [comment]
Wow! Amazing! Thanks, will merge it right away!

**Comment by shuuji3** [comment]
Better TweetDeck is really useful. Thank you for your creation! 😄

**Comment by eramdam** [comment]
Can I count on you if I need new ja locales in the future? 😛

**Comment by shuuji3** [comment]
Yes, off course!

**Pull request merged**
