### PR TITLE
Keep tweeted hashtags

### PR DESCRIPTION
**Pull request by zenmaibane**
Keep tweeted hashtags in tweet textarea.

This is useful when user want to tweet using same hastags many times 

This run like this.
https://i.imgur.com/7V8ZLIH.gif

### CODE REVIEW

**Comment by shuuji3** [comment]
Thank you zenmaibane-san! I also want this feature recently and think to implement it. ☺

**Comment by shuuji3** [comment]
Thank you zenmaibane-san! I also want this feature recently and think to implement it. ☺

**Comment by shuuji3** [comment]
Thank you zenmaibane-san! I also want this feature recently and think to implement it. ☺

**Comment by shuuji3** [comment]
I'm using this feature in my private branch and it's very useful. Thank you.

But I found a case where the feature doesn't work expected. For example, when the status text is "#hashtag some tweet text" (text doesn't start with a space), the regex cannot extract hashtags properly.

So I recommend using Twitter's official "twitter-text" package to extract hashtags so that we can support Twitter's future update! I wrote sample code for reference here: 

RunKit + npm: twitter-text
https://runkit.com/embed/jnqa82ekbsrw

**Comment by pixeldesu** [comment]
As a small tip, if you want to use twitter-text, you don't need to add the npm-module to BTD (if you extract the hashtags on the page itself) because there is a reference to twitter-text located in `window.twttrTxt` on TweetDeck!

**Comment by shuuji3** [comment]
@pixeldesu Thank you for a nice tip! 

I confirmed extraction worked properly with:
```javascript
twttrTxt.extractHashtags(tweetText)
```
insted of 
```javascript
twitterText.extractHashtags(tweetText)
```

**Comment by zenmaibane** [comment]
Thank you for your kind advice!  I didn't know those.
so, I will try using those func :)

**Comment by eramdam** [comment]
Ok so, sorry for being slow to react on this PR, was kinda busy with $dayjob and other things 😅 

So far this PR looks good to me, I only have one concern, but it's probably baseless: 
How do you remove the kept hashtags? Just remove it from the textbox? That's it? 

I tend to think that an implementation like [Tweetbot's topics](https://www.macstories.net/reviews/tweetbot-4-3-introduces-topics-for-easier-tweetstorm-creation/) could be nice, but it's obviously harder to do since there'd be some UI work involved. Maybe I'm seeing inconveniences where there are not, let me know what you think 😄

**Comment by zenmaibane** [comment]
Thank you for review!!

I also feel that the behavior like Tweetbot's topics is more convenient. 
However, when "hashtags input" is newly created, I did not know how to apply the suggestion function of hashtag (originally present in TweetDeck).
(The suggestion function of hashtag is like https://imgur.com/T0gdUzW)

So,  I adopted this implementation method.

**Comment by eramdam** [comment]
@zenmaibane ok, that's how I understood it then. I'll merge that as is and put it on the beta channel for the few people on the program to test (let me know if you want an access to the Discord/beta extension)

**Comment by zenmaibane** [comment]
@eramdam Thank you for the merge! 

I'm interested Discord/beta extension.

**Pull request merged**
